#!/bin/sh
repo="fredblgr"
image="framac"
tag="2021"

args="cd /workspace; `basename $0` $*"

if [[ `uname` == "Darwin" ]]
then
  open -a XQuartz
fi
xhost +localhost

docker run --rm --tty \
           --volume "$(PWD):/workspace:rw" \
           --name "$image$tag" \
           --env="DISPLAY=host.docker.internal:0" \
           $repo/$image:$tag \
       sh -c "${args}"
