#!/bin/sh
repo="fredblgr"
image="framac"
tag="2021"

args="`basename $0` $*"

docker run --rm --tty \
           --volume "$(PWD):/workspace:rw" \
           --name "$image$tag" \
           --workdir /workspace \
           $repo/$image:$tag \
       ${args}
