#!/bin/sh
repo="fredblgr"
image="framac"
tag="2021"

args="`basename $0`"

for a in $*
do
  case $a in
    ide) args="$args ide"
         if [ "`uname`" = "Darwin" ]
         then
           open -a XQuartz
         fi
         xhost +localhost
    ;;
    
    *)   args="$args $a"
    ;;
  esac
done
docker run --rm --tty \
           --volume "$(PWD):/workspace:rw" \
           --name "$image$tag" \
           --env="DISPLAY=host.docker.internal:0" \
           --workdir /workspace \
           $repo/$image:$tag \
       ${args}
